name: Publish Features

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # Needed for GHCR

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Publish Features
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          oci-registry: ghcr.io
          features-namespace: ${{ github.repository_owner }}/devcontainer-features